### ISSUE TITLE
Confusing error (panic) when writing to a broken stdout/pipe

### ISSUE THREAD

**Issue by mozzieongit** [NLnetLabs/dnst#49]
While accidentally piping dnst output into an already exited program (it failed due to invalid arguments), dnst panics, as https://github.com/NLnetLabs/dnst/blob/6f0e27d3e15547818466152790787122e644432b/src/env/mod.rs#L71 uses unwrap on the output stream.
This leads to an ugly error that was confusing at first.
```
$ target/release/dnst nsec3-hash hi | sort -k1s
sort: stray character in field spec: invalid field specification ‘1s’
thread 'main' panicked at /home/mozzie/repos/work/dnst.trees/main/src/env/mod.rs:71:32:
called `Result::unwrap()` on an `Err` value: Error
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Maybe this should change to either:
1. an attempt to write to stderr that writing to stdout failed (if that also fails, ignore and proceed to exit), and exit with an error code; or
2. just exit with an error code

**Comment by ximon18** [comment]
Good catch.

Interesting that it happens at an unwrap that was deliberately ignored.

I vote for option 1 as I've see other programs behave that way, because it has some chance of alerting the user to the reason for the program exiting which otherwise could be confusing.

**Comment by mozzieongit** [comment]
Ignoring it deliberately was inspired by the rust std library, but it was missed that the std library catches the error and panics purposefully with a error message (other than "unwrapped an error value").

So Option 3: do it like rust' std library:
```
$ rustc println.rs && ./println | true                                                
thread 'main' panicked at library/std/src/io/stdio.rs:1118:9:
failed printing to stdout: Broken pipe (os error 32)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

From [rust-lang/rust io/stdio.rs](https://github.com/rust-lang/rust/blob/77b2fe19443ea44fabc3b4221b429165d4137804/library/std/src/io/stdio.rs#L1113-L1125)
```
if let Err(e) = global_s().write_fmt(args) {
    panic!("failed printing to {label}: {e}");
}
```

But I agree on the vote for option 1: attempt to print to stderr; the panic could be too scary for users.
